"""creating student table

Revision ID: 1592fb06ca9f
Revises: 6d56ebcd6bd1
Create Date: 2021-07-26 16:52:27.074798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1592fb06ca9f'
down_revision = '6d56ebcd6bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('s_course_id', sa.Integer(), nullable=False),
    sa.Column('date_enrolled', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['s_course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_course')
    # ### end Alembic commands ###
